[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Configuración de secrets scanning
[build.processing]
  skip_processing = false

# Omitir la detección de secretos en la clave pública de Izipay (es una clave de prueba)
[build.processing.secrets_scanning]
  omit_keys = ["IZIPAY_MERCHANT_ID"]
